# https://typeofnan.dev/how-to-serve-a-vue-app-with-nginx-in-docker/

# Name the node stage "builder"
FROM node:lts-alpine AS builder

# Set working directory
WORKDIR /app

# Copy all files from current directory to working dir in image
COPY . .

# install node modules and build assets
RUN yarn install && yarn build


# nginx state for serving content
FROM nginx:stable-alpine
LABEL maintainer="Sebastian Spreizer <spreizer@web.de>"

# Add default to available sites
COPY ./nginx-default.conf /etc/nginx/conf.d/default.conf

# Remove default nginx static assets
RUN rm -rf /usr/share/nginx/html/*

# Copy static from installer stage
COPY --from=builder /app/nest_desktop/app/ /usr/share/nginx/html/

# Containers run nginx with global directives and daemon off
ENTRYPOINT ["nginx", "-g", "daemon off;"]
