name: Code quality
on: 
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  install-node-modules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: corepack enable
      - uses: actions/setup-node@v7
        with:
          node-version-file: .nvmrc
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
          # package-manager-cache: false # Disable automatic npm caching if not required

      - name: Cache node_modules
        id: cache
        uses: actions/cache@v6
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install node modules
        run: pnpm install --ignore-scripts

  lint:
    runs-on: ubuntu-latest
    needs: [install-node-modules]
    steps:
      - uses: actions/checkout@v7
      - run: corepack enable
      - uses: actions/setup-node@v7
        with:
          node-version-file: .nvmrc
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Cache node_modules
        id: cache
        uses: actions/cache@v6
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install node modules
        run: pnpm install --ignore-scripts

      - name: Run lint check
        run: pnpm lint

      # - name: Run linters
      #   uses: wearerequired/lint-action@v3
      #   with:
      #     eslint: true
      #     prettier: true

  format:
    runs-on: ubuntu-latest
    needs: [install-node-modules]
    steps:
      - uses: actions/checkout@v7
      - run: corepack enable
      - uses: actions/setup-node@v7
        with:
          node-version-file: .nvmrc
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Cache node_modules
        id: cache
        uses: actions/cache@v6
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install node modules
        run: pnpm install --ignore-scripts

      - name: Run format check
        run: pnpm format:check

  type-checking:
    runs-on: ubuntu-latest
    needs: [install-node-modules]
    steps:
      - uses: actions/checkout@v7
      - run: corepack enable
      - uses: actions/setup-node@v7
        with:
          node-version-file: .nvmrc
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Cache node_modules
        id: cache
        uses: actions/cache@v6
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install node modules
        run: pnpm install --ignore-scripts

      - name: Type check
        run: pnpm run vue-tsc --noEmit