name: Code quality
on: 
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/setup@v3
        with:
          version: 12
          cache: true

      - name: Run lint check
        run: pnpm lint

  format:
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/setup@v3
        with:
          version: 12
          cache: true

      - name: Run format check
        run: pnpm format

  type-checking:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/setup@v3
        with:
          version: 12
          cache: true

      - name: Run type check
        run: pnpm type-check

